// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFsNcUmbDo3YnIi3TvMq-q9hZXZFSvgWc',
    appId: '1:131925744771:web:f5fb9260f934aea0c4cfb6',
    messagingSenderId: '131925744771',
    projectId: 'ai-productivity-super-ap-71736',
    authDomain: 'ai-productivity-super-ap-71736.firebaseapp.com',
    storageBucket: 'ai-productivity-super-ap-71736.firebasestorage.app',
    measurementId: 'G-R3M2ZQNC2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM6IEOsFlsvy68eUSxrRWY-iwVj4IPouI',
    appId: '1:131925744771:android:e3880e9a800eb97ac4cfb6',
    messagingSenderId: '131925744771',
    projectId: 'ai-productivity-super-ap-71736',
    storageBucket: 'ai-productivity-super-ap-71736.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY-tQfs2AUyeBpltYOCu7IbADIbf4oOGI',
    appId: '1:131925744771:ios:b929fe4ce5869aa4c4cfb6',
    messagingSenderId: '131925744771',
    projectId: 'ai-productivity-super-ap-71736',
    storageBucket: 'ai-productivity-super-ap-71736.firebasestorage.app',
    iosBundleId: 'com.example.aiProductivitySuperApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY-tQfs2AUyeBpltYOCu7IbADIbf4oOGI',
    appId: '1:131925744771:ios:b929fe4ce5869aa4c4cfb6',
    messagingSenderId: '131925744771',
    projectId: 'ai-productivity-super-ap-71736',
    storageBucket: 'ai-productivity-super-ap-71736.firebasestorage.app',
    iosBundleId: 'com.example.aiProductivitySuperApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFsNcUmbDo3YnIi3TvMq-q9hZXZFSvgWc',
    appId: '1:131925744771:web:67c94716d58311f5c4cfb6',
    messagingSenderId: '131925744771',
    projectId: 'ai-productivity-super-ap-71736',
    authDomain: 'ai-productivity-super-ap-71736.firebaseapp.com',
    storageBucket: 'ai-productivity-super-ap-71736.firebasestorage.app',
    measurementId: 'G-0QXNPKN3JJ',
  );
}
